before_script:
  - pwd
  - type multiwerf && source <(multiwerf use 1.1 beta)
  - type werf && source <(werf ci-env gitlab --tagging-strategy tag-or-branch --verbose)

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

stages:
  - build

build:
  stage: build
  script:
    - werf build-and-publish --stages-storage :local
  tags:
    - werf
  except:
    - schedules
