FROM registry.project-karma.com/karma/application/common/node:14
WORKDIR /application
COPY src /application
COPY htdocs /application
COPY build /application
RUN npm ci --only-production

ENV SOURCE=htdocs/explorer
CMD node server.js