#!/bin/bash

CHAINCODE_NAME=$1
CHAINCODE_VERSION=$2
CHAINCODE_LANG=$3
CHAINCODE_PATH=$4

CHAINCODE_LABEL="${CHAINCODE_NAME}_${CHAINCODE_VERSION}"
PACKAGE_FILE_PATH="${CHAINCODE_PATH}/${CHAINCODE_NAME}.tar.gz"

set -x
docker exec cli peer lifecycle chaincode package \
  "${PACKAGE_FILE_PATH}" \
  --lang "${CHAINCODE_LANG}" \
  --path "${CHAINCODE_PATH}" \
  --label "${CHAINCODE_LABEL}"
