volume:
  name: hlf-volume

env:
  NODE_ENV: development
  LOGGER_LEVEL: 3
  POSTGRES_DB_HOST: hlf-explorer-db-svc
  POSTGRES_DB_PORT: 5432
  POSTGRES_DB: hlf-explorer
  POSTGRES_USER: hlf-explorer
  POSTGRES_PASSWORD: hlf-explorer
  WEB_HOST: localhost
  WEB_PORT: 3000
  LEDGERS_SETTINGS_PATH: /application/build/data/ledgers.json

mounts:
  - mountPath: /application/build/data
    subPath: backend/hlf-explorer/data

imagePullSecrets: regcred
